### ISSUE TITLE
Generate does not fail fast when the ingest ldd file is missing

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/ldd-manager#2]
## 🐛 Describe the bug
When the Ingest LDD file in an LDD repo does not exist, or does not match the naming convention, the build action fails with a Java null pointer exception when running lddtool, as can be seen here:

https://github.com/pds-data-dictionaries/ldd-dawn/issues/4
https://github.com/pds-data-dictionaries/ldd-dawn/actions/runs/3324858939/jobs/5497194998#step:18:235

## 📜 To Reproduce
1. Create a new branch in one of the pds-data-dictionaries repos
2. Delete or rename the ingestLDD file
3. Check the build logs

## 🕵️ Expected behavior
I think that the `find_primary_ingest_ldd ` could check the value of `ingest_ldd` before returning it, and fail with a better error message if it doesn't find an ingest LDD.

## 📚 Version of Software Used
NA

## 🩺 Test Data / Additional context
NA

##  🏞Screenshots
<img width="663" alt="Screen Shot 2022-10-26 at 9 23 14 AM" src="https://user-images.githubusercontent.com/25939961/198081259-a66036a6-0a09-4a96-a20a-5109da8ee349.png">

## 🖥 System Info
NA

---

**Comment by jordanpadams** [comment]
@jstone-psi copy. will add this to the list
